[package]
name = "HelloWorldRust"
version = "0.1.0"
authors = ["Степан <dimebag1997@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
